### ISSUE TITLE
HTML Code changed?

### ISSUE THREAD

**Issue by RatzeR** [kennell/schiene#17]
I think the html on the db website has changed.

`Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 244, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 327, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/deutsche_bahn.py", line 82, in update
    self.data.update()
  File "/usr/lib/python3.6/site-packages/homeassistant/components/sensor/deutsche_bahn.py", line 105, in update
    self.only_direct)
  File "/usr/lib/python3.6/site-packages/schiene/schiene.py", line 135, in connections
    return parse_connections(rsp.text)
  File "/usr/lib/python3.6/site-packages/schiene/schiene.py", line 35, in parse_connections
    data = parse_delay(data)
  File "/usr/lib/python3.6/site-packages/schiene/schiene.py", line 65, in parse_delay
    delay_arrival_raw = soup.find('div', class_="routeEnd").find('span', class_=["delay", "delayOnTime"])
AttributeError: 'NoneType' object has no attribute 'find'`

**Comment by nedy13** [comment]
I have got the same problem quite often. Sometimes it works and sometimes not. I think about a retry mechanism in my code. Maybe a temporary problem of the DB side.
