### ISSUE TITLE
Problem with Wolfbusch Station

### ISSUE THREAD

**Issue by Iskenof** [kennell/schiene#18]
python
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import schiene
>>> s = schiene.Schiene()
>>> s.connections('Wolfbusch, Stuttgart', 'Stuttgart-Feuerbach')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/schiene/schiene.py", line 135, in connections
    return parse_connections(rsp.text)
  File "/usr/local/lib/python2.7/dist-packages/schiene/schiene.py", line 35, in parse_connections
    data = parse_delay(data)
  File "/usr/local/lib/python2.7/dist-packages/schiene/schiene.py", line 65, in parse_delay
    delay_arrival_raw = soup.find('div', class_="routeEnd").find('span', class_=["delay", "delayOnTime"])
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by kennell** [comment]
Can confirm the error; but currently on a tight schedule so i can't give you a estimate on when i get around fixing this

**Comment by kennell** [comment]
Fixed in https://github.com/kennell/schiene/pull/20, released on PyPI as version `0.23`
