### ISSUE TITLE
TypeError: unsupported operand type

### ISSUE THREAD

**Issue by kgroshert** [kennell/schiene#34]
I just started getting this error-message when trying get a connection.
Other destinations seem to work (e.g. 'Mannheim HbF' to 'Stuttgart HbF').
Is there anything I can check?

`$ python3
Python 3.7.3 (default, Oct 31 2022, 14:04:00) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import schiene
>>> s = schiene.Schiene()
>>> s.connections('Wernau(neckar)', 'Wendlingen(neckar)')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dev/.local/lib/python3.7/site-packages/schiene/schiene.py", line 150, in connections
    return parse_connections(rsp.text)
  File "/home/dev/.local/lib/python3.7/site-packages/schiene/schiene.py", line 35, in parse_connections
    data = parse_delay(data)
  File "/home/dev/.local/lib/python3.7/site-packages/schiene/schiene.py", line 65, in parse_delay
    delay_departure_raw.text)
  File "/home/dev/.local/lib/python3.7/site-packages/schiene/schiene.py", line 106, in calculate_delay
    diff = fullday - original + delayed
TypeError: unsupported operand type(s) for -: 'int' and 'datetime.datetime'`

**Comment by kgroshert** [comment]
This morning, the error is gone. Not sure what happened with the DB HTML 🤷‍♂️
Should I close the issue or is there something useful to be read from the python error-message?

**Comment by kennell** [comment]
I will close for now, thank you for reporting.
